/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FSC
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod/mini"

export const FscNumberText = /*#__PURE__*/ zod.union([
  /*#__PURE__*/ zod.string(),
  /*#__PURE__*/ zod.number(),
])

export type FscNumberText = zod.input<typeof FscNumberText>
export type FscNumberTextOutput = zod.output<typeof FscNumberText>

export const FscOptionalNumberText = /*#__PURE__*/ zod.union([
  /*#__PURE__*/ zod.string(),
  /*#__PURE__*/ zod.number(),
  /*#__PURE__*/ zod.null(),
])

export type FscOptionalNumberText = zod.input<typeof FscOptionalNumberText>
export type FscOptionalNumberTextOutput = zod.output<
  typeof FscOptionalNumberText
>

export const fscStockPriceItemBasDtRegExp = new RegExp("^[0-9]{8}$")

export const FscStockPriceItem = /*#__PURE__*/ zod.object({
  basDt: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(fscStockPriceItemBasDtRegExp)),
  srtnCd: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  isinCd: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1))
  ),
  itmsNm: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  mrktCtg: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  clpr: FscNumberText,
  fltRt: FscNumberText,
  mkp: FscNumberText,
  hipr: FscNumberText,
  lopr: FscNumberText,
  trqu: FscNumberText,
  trPrc: FscNumberText,
  lstgStCnt: FscNumberText,
  mrktTotAmt: FscNumberText,
})

export type FscStockPriceItem = zod.input<typeof FscStockPriceItem>
export type FscStockPriceItemOutput = zod.output<typeof FscStockPriceItem>

export const fscMarketIndexItemBasDtRegExp = new RegExp("^[0-9]{8}$")

export const FscMarketIndexItem = /*#__PURE__*/ zod.object({
  basDt: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(fscMarketIndexItemBasDtRegExp)),
  idxNm: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  clpr: FscNumberText,
  fltRt: FscNumberText,
  trPrc: /*#__PURE__*/ zod.optional(FscOptionalNumberText),
  lstgMrktTotAmt: /*#__PURE__*/ zod.optional(FscOptionalNumberText),
})

export type FscMarketIndexItem = zod.input<typeof FscMarketIndexItem>
export type FscMarketIndexItemOutput = zod.output<typeof FscMarketIndexItem>

export const FscSuccessHeader = /*#__PURE__*/ zod.object({
  resultCode: /*#__PURE__*/ zod.literal("00"),
  resultMsg: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
})

export type FscSuccessHeader = zod.input<typeof FscSuccessHeader>
export type FscSuccessHeaderOutput = zod.output<typeof FscSuccessHeader>

export const FscStockPriceResponse = /*#__PURE__*/ zod.object({
  response: /*#__PURE__*/ zod.object({
    header: FscSuccessHeader,
    body: /*#__PURE__*/ zod.object({
      items: /*#__PURE__*/ zod.optional(
        /*#__PURE__*/ zod.object({
          item: /*#__PURE__*/ zod.optional(
            /*#__PURE__*/ zod.union([
              /*#__PURE__*/ zod.array(FscStockPriceItem),
              FscStockPriceItem,
            ])
          ),
        })
      ),
    }),
  }),
})

export type FscStockPriceResponse = zod.input<typeof FscStockPriceResponse>
export type FscStockPriceResponseOutput = zod.output<
  typeof FscStockPriceResponse
>

export const FscMarketIndexResponse = /*#__PURE__*/ zod.object({
  response: /*#__PURE__*/ zod.object({
    header: FscSuccessHeader,
    body: /*#__PURE__*/ zod.object({
      items: /*#__PURE__*/ zod.optional(
        /*#__PURE__*/ zod.object({
          item: /*#__PURE__*/ zod.optional(
            /*#__PURE__*/ zod.union([
              /*#__PURE__*/ zod.array(FscMarketIndexItem),
              FscMarketIndexItem,
            ])
          ),
        })
      ),
    }),
  }),
})

export type FscMarketIndexResponse = zod.input<typeof FscMarketIndexResponse>
export type FscMarketIndexResponseOutput = zod.output<
  typeof FscMarketIndexResponse
>

export const FscErrorResponse = /*#__PURE__*/ zod.object({
  response: /*#__PURE__*/ zod.object({
    header: /*#__PURE__*/ zod.object({
      resultCode: /*#__PURE__*/ zod.string(),
      resultMsg: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
    }),
  }),
})

export type FscErrorResponse = zod.input<typeof FscErrorResponse>
export type FscErrorResponseOutput = zod.output<typeof FscErrorResponse>
export const fscStockPriceInfoQueryBasDtRegExp = new RegExp("^[0-9]{8}$")

export const FscStockPriceInfoQueryParams = /*#__PURE__*/ zod.object({
  serviceKey: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  resultType: /*#__PURE__*/ zod.literal("json"),
  basDt: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(fscStockPriceInfoQueryBasDtRegExp)),
  numOfRows: /*#__PURE__*/ zod.literal("5000"),
  pageNo: /*#__PURE__*/ zod.literal("1"),
})

export const FscStockPriceInfo200Response = /*#__PURE__*/ zod.union([
  FscStockPriceResponse,
  FscErrorResponse,
])

export const FscStockPriceInfoDefaultResponse = FscErrorResponse

export const fscMarketIndexInfoQueryBasDtRegExp = new RegExp("^[0-9]{8}$")

export const FscMarketIndexInfoQueryParams = /*#__PURE__*/ zod.object({
  serviceKey: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  resultType: /*#__PURE__*/ zod.literal("json"),
  basDt: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(fscMarketIndexInfoQueryBasDtRegExp)),
  numOfRows: /*#__PURE__*/ zod.literal("200"),
  pageNo: /*#__PURE__*/ zod.literal("1"),
})

export const FscMarketIndexInfo200Response = /*#__PURE__*/ zod.union([
  FscMarketIndexResponse,
  FscErrorResponse,
])

export const FscMarketIndexInfoDefaultResponse = FscErrorResponse

const fscStockPriceInfoContract = {
  method: "get",
  path: "/1160100/service/GetStockSecuritiesInfoService/getStockPriceInfo",
  request: {
    query: FscStockPriceInfoQueryParams,
  },
  responses: {
    "200": {
      schema: FscStockPriceInfo200Response,
      success: FscStockPriceResponse,
      failures: [FscErrorResponse],
    },
    default: {
      schema: FscStockPriceInfoDefaultResponse,
    },
  },
} as const

const fscMarketIndexInfoContract = {
  method: "get",
  path: "/1160100/service/GetMarketIndexInfoService/getStockMarketIndex",
  request: {
    query: FscMarketIndexInfoQueryParams,
  },
  responses: {
    "200": {
      schema: FscMarketIndexInfo200Response,
      success: FscMarketIndexResponse,
      failures: [FscErrorResponse],
    },
    default: {
      schema: FscMarketIndexInfoDefaultResponse,
    },
  },
} as const

export const rest = {
  fscStockPriceInfo: fscStockPriceInfoContract,
  fscMarketIndexInfo: fscMarketIndexInfoContract,
} as const
