/**
 * Generated by orval 🍺
 * Do not edit manually.
 * KIS REST API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod/mini"

export const kisRestErrorResponseRtCdRegExp = new RegExp("^(?!0$)[\\s\\S]*$")

export const KisRestErrorResponse = /*#__PURE__*/ zod.object({
  rt_cd: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(kisRestErrorResponseRtCdRegExp)),
  msg_cd: /*#__PURE__*/ zod.string(),
  msg1: /*#__PURE__*/ zod.string(),
})

export type KisRestErrorResponse = zod.input<typeof KisRestErrorResponse>
export type KisRestErrorResponseOutput = zod.output<typeof KisRestErrorResponse>

export const KisOAuthErrorResponse = /*#__PURE__*/ zod.object({
  error_code: /*#__PURE__*/ zod.string(),
  error_description: /*#__PURE__*/ zod.string(),
})

export type KisOAuthErrorResponse = zod.input<typeof KisOAuthErrorResponse>
export type KisOAuthErrorResponseOutput = zod.output<
  typeof KisOAuthErrorResponse
>

export const AuthTokenRequest = /*#__PURE__*/ zod.object({
  grant_type: /*#__PURE__*/ zod.literal("client_credentials"),
  appkey: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  appsecret: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
})

export type AuthTokenRequest = zod.input<typeof AuthTokenRequest>
export type AuthTokenRequestOutput = zod.output<typeof AuthTokenRequest>

export const AuthTokenResponse = /*#__PURE__*/ zod.object({
  access_token: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1)),
  token_type: /*#__PURE__*/ zod.string(),
  expires_in: /*#__PURE__*/ zod.int().check(/*#__PURE__*/ zod.gte(1)),
  access_token_token_expired: /*#__PURE__*/ zod.string(),
})

export type AuthTokenResponse = zod.input<typeof AuthTokenResponse>
export type AuthTokenResponseOutput = zod.output<typeof AuthTokenResponse>

export const AuthWsTokenRequest = /*#__PURE__*/ zod.object({
  grant_type: /*#__PURE__*/ zod.literal("client_credentials"),
  appkey: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  secretkey: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  token: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
})

export type AuthWsTokenRequest = zod.input<typeof AuthWsTokenRequest>
export type AuthWsTokenRequestOutput = zod.output<typeof AuthWsTokenRequest>

export const AuthWsTokenResponse = /*#__PURE__*/ zod.object({
  approval_key: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1)),
})

export type AuthWsTokenResponse = zod.input<typeof AuthWsTokenResponse>
export type AuthWsTokenResponseOutput = zod.output<typeof AuthWsTokenResponse>

export const DomesticStockInquirePriceResponse = /*#__PURE__*/ zod.object({
  rt_cd: /*#__PURE__*/ zod.literal("0"),
  msg_cd: /*#__PURE__*/ zod.string(),
  msg1: /*#__PURE__*/ zod.string(),
  output: /*#__PURE__*/ zod.object({
    iscd_stat_cls_code: /*#__PURE__*/ zod.string(),
    marg_rate: /*#__PURE__*/ zod.string(),
    rprs_mrkt_kor_name: /*#__PURE__*/ zod.string(),
    new_hgpr_lwpr_cls_code: /*#__PURE__*/ zod.string(),
    bstp_kor_isnm: /*#__PURE__*/ zod.string(),
    temp_stop_yn: /*#__PURE__*/ zod.string(),
    oprc_rang_cont_yn: /*#__PURE__*/ zod.string(),
    clpr_rang_cont_yn: /*#__PURE__*/ zod.string(),
    crdt_able_yn: /*#__PURE__*/ zod.string(),
    grmn_rate_cls_code: /*#__PURE__*/ zod.string(),
    elw_pblc_yn: /*#__PURE__*/ zod.string(),
    stck_prpr: /*#__PURE__*/ zod.string(),
    prdy_vrss: /*#__PURE__*/ zod.string(),
    prdy_vrss_sign: /*#__PURE__*/ zod.string(),
    prdy_ctrt: /*#__PURE__*/ zod.string(),
    acml_tr_pbmn: /*#__PURE__*/ zod.string(),
    acml_vol: /*#__PURE__*/ zod.string(),
    prdy_vrss_vol_rate: /*#__PURE__*/ zod.string(),
    stck_oprc: /*#__PURE__*/ zod.string(),
    stck_hgpr: /*#__PURE__*/ zod.string(),
    stck_lwpr: /*#__PURE__*/ zod.string(),
    stck_mxpr: /*#__PURE__*/ zod.string(),
    stck_llam: /*#__PURE__*/ zod.string(),
    stck_sdpr: /*#__PURE__*/ zod.string(),
    wghn_avrg_stck_prc: /*#__PURE__*/ zod.string(),
    hts_frgn_ehrt: /*#__PURE__*/ zod.string(),
    frgn_ntby_qty: /*#__PURE__*/ zod.string(),
    pgtr_ntby_qty: /*#__PURE__*/ zod.string(),
    pvt_scnd_dmrs_prc: /*#__PURE__*/ zod.string(),
    pvt_frst_dmrs_prc: /*#__PURE__*/ zod.string(),
    pvt_pont_val: /*#__PURE__*/ zod.string(),
    pvt_frst_dmsp_prc: /*#__PURE__*/ zod.string(),
    pvt_scnd_dmsp_prc: /*#__PURE__*/ zod.string(),
    dmrs_val: /*#__PURE__*/ zod.string(),
    dmsp_val: /*#__PURE__*/ zod.string(),
    cpfn: /*#__PURE__*/ zod.string(),
    rstc_wdth_prc: /*#__PURE__*/ zod.string(),
    stck_fcam: /*#__PURE__*/ zod.string(),
    stck_sspr: /*#__PURE__*/ zod.string(),
    aspr_unit: /*#__PURE__*/ zod.string(),
    hts_deal_qty_unit_val: /*#__PURE__*/ zod.string(),
    lstn_stcn: /*#__PURE__*/ zod.string(),
    hts_avls: /*#__PURE__*/ zod.string(),
    per: /*#__PURE__*/ zod.string(),
    pbr: /*#__PURE__*/ zod.string(),
    stac_month: /*#__PURE__*/ zod.string(),
    vol_tnrt: /*#__PURE__*/ zod.string(),
    eps: /*#__PURE__*/ zod.string(),
    bps: /*#__PURE__*/ zod.string(),
    d250_hgpr: /*#__PURE__*/ zod.string(),
    d250_hgpr_date: /*#__PURE__*/ zod.string(),
    d250_hgpr_vrss_prpr_rate: /*#__PURE__*/ zod.string(),
    d250_lwpr: /*#__PURE__*/ zod.string(),
    d250_lwpr_date: /*#__PURE__*/ zod.string(),
    d250_lwpr_vrss_prpr_rate: /*#__PURE__*/ zod.string(),
    stck_dryy_hgpr: /*#__PURE__*/ zod.string(),
    dryy_hgpr_vrss_prpr_rate: /*#__PURE__*/ zod.string(),
    dryy_hgpr_date: /*#__PURE__*/ zod.string(),
    stck_dryy_lwpr: /*#__PURE__*/ zod.string(),
    dryy_lwpr_vrss_prpr_rate: /*#__PURE__*/ zod.string(),
    dryy_lwpr_date: /*#__PURE__*/ zod.string(),
    w52_hgpr: /*#__PURE__*/ zod.string(),
    w52_hgpr_vrss_prpr_ctrt: /*#__PURE__*/ zod.string(),
    w52_hgpr_date: /*#__PURE__*/ zod.string(),
    w52_lwpr: /*#__PURE__*/ zod.string(),
    w52_lwpr_vrss_prpr_ctrt: /*#__PURE__*/ zod.string(),
    w52_lwpr_date: /*#__PURE__*/ zod.string(),
    whol_loan_rmnd_rate: /*#__PURE__*/ zod.string(),
    ssts_yn: /*#__PURE__*/ zod.string(),
    stck_shrn_iscd: /*#__PURE__*/ zod.string(),
    fcam_cnnm: /*#__PURE__*/ zod.string(),
    cpfn_cnnm: /*#__PURE__*/ zod.string(),
    apprch_rate: /*#__PURE__*/ zod.string(),
    frgn_hldn_qty: /*#__PURE__*/ zod.string(),
    vi_cls_code: /*#__PURE__*/ zod.string(),
    ovtm_vi_cls_code: /*#__PURE__*/ zod.string(),
    last_ssts_cntg_qty: /*#__PURE__*/ zod.string(),
    invt_caful_yn: /*#__PURE__*/ zod.string(),
    mrkt_warn_cls_code: /*#__PURE__*/ zod.string(),
    short_over_yn: /*#__PURE__*/ zod.string(),
    sltr_yn: /*#__PURE__*/ zod.string(),
    mang_issu_cls_code: /*#__PURE__*/ zod.string(),
  }),
})

export type DomesticStockInquirePriceResponse = zod.input<
  typeof DomesticStockInquirePriceResponse
>
export type DomesticStockInquirePriceResponseOutput = zod.output<
  typeof DomesticStockInquirePriceResponse
>

export const DomesticStockInquireDailyItemChartPriceResponse =
  /*#__PURE__*/ zod.object({
    rt_cd: /*#__PURE__*/ zod.literal("0"),
    msg_cd: /*#__PURE__*/ zod.string(),
    msg1: /*#__PURE__*/ zod.string(),
    output1: /*#__PURE__*/ zod.object({
      prdy_vrss: /*#__PURE__*/ zod.string(),
      prdy_vrss_sign: /*#__PURE__*/ zod.string(),
      prdy_ctrt: /*#__PURE__*/ zod.string(),
      stck_prdy_clpr: /*#__PURE__*/ zod.string(),
      acml_vol: /*#__PURE__*/ zod.string(),
      acml_tr_pbmn: /*#__PURE__*/ zod.string(),
      hts_kor_isnm: /*#__PURE__*/ zod.string(),
      stck_prpr: /*#__PURE__*/ zod.string(),
      stck_shrn_iscd: /*#__PURE__*/ zod.string(),
      prdy_vol: /*#__PURE__*/ zod.string(),
      stck_mxpr: /*#__PURE__*/ zod.string(),
      stck_llam: /*#__PURE__*/ zod.string(),
      stck_oprc: /*#__PURE__*/ zod.string(),
      stck_hgpr: /*#__PURE__*/ zod.string(),
      stck_lwpr: /*#__PURE__*/ zod.string(),
      stck_prdy_oprc: /*#__PURE__*/ zod.string(),
      stck_prdy_hgpr: /*#__PURE__*/ zod.string(),
      stck_prdy_lwpr: /*#__PURE__*/ zod.string(),
      askp: /*#__PURE__*/ zod.string(),
      bidp: /*#__PURE__*/ zod.string(),
      prdy_vrss_vol: /*#__PURE__*/ zod.string(),
      vol_tnrt: /*#__PURE__*/ zod.string(),
      stck_fcam: /*#__PURE__*/ zod.string(),
      lstn_stcn: /*#__PURE__*/ zod.string(),
      cpfn: /*#__PURE__*/ zod.string(),
      hts_avls: /*#__PURE__*/ zod.string(),
      per: /*#__PURE__*/ zod.string(),
      eps: /*#__PURE__*/ zod.string(),
      pbr: /*#__PURE__*/ zod.string(),
      itewhol_loan_rmnd_ratem: /*#__PURE__*/ zod.string(),
    }),
    output2: /*#__PURE__*/ zod.array(
      /*#__PURE__*/ zod.object({
        stck_bsop_date: /*#__PURE__*/ zod.string(),
        stck_clpr: /*#__PURE__*/ zod.string(),
        stck_oprc: /*#__PURE__*/ zod.string(),
        stck_hgpr: /*#__PURE__*/ zod.string(),
        stck_lwpr: /*#__PURE__*/ zod.string(),
        acml_vol: /*#__PURE__*/ zod.string(),
        acml_tr_pbmn: /*#__PURE__*/ zod.string(),
        flng_cls_code: /*#__PURE__*/ zod.string(),
        prtt_rate: /*#__PURE__*/ zod.string(),
        mod_yn: /*#__PURE__*/ zod.string(),
        prdy_vrss_sign: /*#__PURE__*/ zod.string(),
        prdy_vrss: /*#__PURE__*/ zod.string(),
        revl_issu_reas: /*#__PURE__*/ zod.string(),
      })
    ),
  })

export type DomesticStockInquireDailyItemChartPriceResponse = zod.input<
  typeof DomesticStockInquireDailyItemChartPriceResponse
>
export type DomesticStockInquireDailyItemChartPriceResponseOutput = zod.output<
  typeof DomesticStockInquireDailyItemChartPriceResponse
>

export const domesticStockChkHolidayResponseOutputItemBassDtRegExp = new RegExp(
  "^[0-9]{8}$"
)

export const DomesticStockChkHolidayResponse = /*#__PURE__*/ zod.object({
  rt_cd: /*#__PURE__*/ zod.literal("0"),
  msg_cd: /*#__PURE__*/ zod.string(),
  msg1: /*#__PURE__*/ zod.string(),
  ctx_area_fk: /*#__PURE__*/ zod.string(),
  ctx_area_nk: /*#__PURE__*/ zod.string(),
  output: /*#__PURE__*/ zod.array(
    /*#__PURE__*/ zod.object({
      bass_dt: /*#__PURE__*/ zod
        .string()
        .check(
          /*#__PURE__*/ zod.regex(
            domesticStockChkHolidayResponseOutputItemBassDtRegExp
          )
        ),
      wday_dvsn_cd: /*#__PURE__*/ zod.string(),
      bzdy_yn: /*#__PURE__*/ zod.enum(["Y", "N"]),
      tr_day_yn: /*#__PURE__*/ zod.enum(["Y", "N"]),
      opnd_yn: /*#__PURE__*/ zod.enum(["Y", "N"]),
      sttl_day_yn: /*#__PURE__*/ zod.enum(["Y", "N"]),
    })
  ),
})

export type DomesticStockChkHolidayResponse = zod.input<
  typeof DomesticStockChkHolidayResponse
>
export type DomesticStockChkHolidayResponseOutput = zod.output<
  typeof DomesticStockChkHolidayResponse
>
/**
 * @summary 접근토큰발급
 */
export const AuthTokenBody = AuthTokenRequest

export const AuthToken200Response = AuthTokenResponse

export const AuthTokenDefaultResponse = KisOAuthErrorResponse

/**
 * @summary 웹소켓 접속키 발급
 */
export const AuthWsTokenBody = AuthWsTokenRequest

export const AuthWsToken200Response = AuthWsTokenResponse

export const AuthWsTokenDefaultResponse = KisRestErrorResponse

/**
 * @summary 주식현재가 시세
 */

export const DomesticStockInquirePriceQueryParams = /*#__PURE__*/ zod.object({
  FID_COND_MRKT_DIV_CODE: /*#__PURE__*/ zod.enum(["J", "NX", "UN"]),
  FID_INPUT_ISCD: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.minLength(1)),
})

export const DomesticStockInquirePriceHeader = /*#__PURE__*/ zod.object({
  tr_id: /*#__PURE__*/ zod.literal("FHKST01010100"),
  custtype: /*#__PURE__*/ zod.literal("P"),
})

export const DomesticStockInquirePrice200Response = /*#__PURE__*/ zod.union([
  DomesticStockInquirePriceResponse,
  KisRestErrorResponse,
])

export const DomesticStockInquirePriceDefaultResponse = KisRestErrorResponse

/**
 * @summary 국내주식기간별시세(일/주/월/년)
 */

export const domesticStockInquireDailyItemChartPriceQueryFIDINPUTDATE1RegExp =
  new RegExp("^[0-9]{8}$")
export const domesticStockInquireDailyItemChartPriceQueryFIDINPUTDATE2RegExp =
  new RegExp("^[0-9]{8}$")

export const DomesticStockInquireDailyItemChartPriceQueryParams =
  /*#__PURE__*/ zod.object({
    FID_COND_MRKT_DIV_CODE: /*#__PURE__*/ zod.enum(["J", "NX", "UN"]),
    FID_INPUT_ISCD: /*#__PURE__*/ zod
      .string()
      .check(/*#__PURE__*/ zod.minLength(1)),
    FID_INPUT_DATE_1: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.regex(
          domesticStockInquireDailyItemChartPriceQueryFIDINPUTDATE1RegExp
        )
      ),
    FID_INPUT_DATE_2: /*#__PURE__*/ zod
      .string()
      .check(
        /*#__PURE__*/ zod.regex(
          domesticStockInquireDailyItemChartPriceQueryFIDINPUTDATE2RegExp
        )
      ),
    FID_PERIOD_DIV_CODE: /*#__PURE__*/ zod.enum(["D", "W", "M", "Y"]),
    FID_ORG_ADJ_PRC: /*#__PURE__*/ zod.enum(["0", "1"]),
  })

export const DomesticStockInquireDailyItemChartPriceHeader =
  /*#__PURE__*/ zod.object({
    tr_id: /*#__PURE__*/ zod.literal("FHKST03010100"),
    custtype: /*#__PURE__*/ zod.literal("P"),
  })

export const DomesticStockInquireDailyItemChartPrice200Response =
  /*#__PURE__*/ zod.union([
    DomesticStockInquireDailyItemChartPriceResponse,
    KisRestErrorResponse,
  ])

export const DomesticStockInquireDailyItemChartPriceDefaultResponse =
  KisRestErrorResponse

/**
 * @summary 국내휴장일조회
 */
export const domesticStockChkHolidayQueryBASSDTRegExp = new RegExp("^[0-9]{8}$")

export const DomesticStockChkHolidayQueryParams = /*#__PURE__*/ zod.object({
  BASS_DT: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(domesticStockChkHolidayQueryBASSDTRegExp)),
  CTX_AREA_FK: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  CTX_AREA_NK: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
})

export const DomesticStockChkHolidayHeader = /*#__PURE__*/ zod.object({
  tr_id: /*#__PURE__*/ zod.literal("CTCA0903R"),
  custtype: /*#__PURE__*/ zod.literal("P"),
  tr_cont: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
})

export const DomesticStockChkHoliday200Response = /*#__PURE__*/ zod.union([
  DomesticStockChkHolidayResponse,
  KisRestErrorResponse,
])

export const DomesticStockChkHolidayDefaultResponse = KisRestErrorResponse

const authTokenContract = {
  method: "post",
  path: "/oauth2/tokenP",
  request: {
    body: AuthTokenBody,
  },
  responses: {
    "200": {
      schema: AuthToken200Response,
    },
    default: {
      schema: AuthTokenDefaultResponse,
    },
  },
} as const

const authWsTokenContract = {
  method: "post",
  path: "/oauth2/Approval",
  request: {
    body: AuthWsTokenBody,
  },
  responses: {
    "200": {
      schema: AuthWsToken200Response,
    },
    default: {
      schema: AuthWsTokenDefaultResponse,
    },
  },
} as const

const domesticStockInquirePriceContract = {
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-price",
  request: {
    query: DomesticStockInquirePriceQueryParams,
    headers: DomesticStockInquirePriceHeader,
    fixedHeaders: {
      tr_id: "FHKST01010100",
      custtype: "P",
    },
  },
  responses: {
    "200": {
      schema: DomesticStockInquirePrice200Response,
      success: DomesticStockInquirePriceResponse,
      failures: [KisRestErrorResponse],
    },
    default: {
      schema: DomesticStockInquirePriceDefaultResponse,
    },
  },
} as const

const domesticStockInquireDailyItemChartPriceContract = {
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice",
  request: {
    query: DomesticStockInquireDailyItemChartPriceQueryParams,
    headers: DomesticStockInquireDailyItemChartPriceHeader,
    fixedHeaders: {
      tr_id: "FHKST03010100",
      custtype: "P",
    },
  },
  responses: {
    "200": {
      schema: DomesticStockInquireDailyItemChartPrice200Response,
      success: DomesticStockInquireDailyItemChartPriceResponse,
      failures: [KisRestErrorResponse],
    },
    default: {
      schema: DomesticStockInquireDailyItemChartPriceDefaultResponse,
    },
  },
} as const

const domesticStockChkHolidayContract = {
  method: "get",
  path: "/uapi/domestic-stock/v1/quotations/chk-holiday",
  request: {
    query: DomesticStockChkHolidayQueryParams,
    headers: DomesticStockChkHolidayHeader,
    fixedHeaders: {
      tr_id: "CTCA0903R",
      custtype: "P",
    },
  },
  responses: {
    "200": {
      schema: DomesticStockChkHoliday200Response,
      success: DomesticStockChkHolidayResponse,
      failures: [KisRestErrorResponse],
    },
    default: {
      schema: DomesticStockChkHolidayDefaultResponse,
    },
  },
} as const

export const rest = {
  authToken: authTokenContract,
  authWsToken: authWsTokenContract,
  domesticStockInquirePrice: domesticStockInquirePriceContract,
  domesticStockInquireDailyItemChartPrice:
    domesticStockInquireDailyItemChartPriceContract,
  domesticStockChkHoliday: domesticStockChkHolidayContract,
} as const
