// Generated from OpenAPI Overlay examples. Do not edit.
import type {
  AuthTokenResponse,
  KisOAuthErrorResponse,
  AuthWsTokenResponse,
  KisRestErrorResponse,
  DomesticStockInquirePriceResponse,
  DomesticStockInquireDailyItemChartPriceResponse,
  DomesticStockChkHolidayResponse,
} from "./api"

export const scenarios = {
  authToken: {
    method: "post",
    path: "/oauth2/tokenP",
    scenarios: {
      success: {
        status: 200,
        body: {
          access_token: "testAccessToken",
          token_type: "Bearer",
          expires_in: 86400,
          access_token_token_expired: "2099-12-31 23:59:59",
        } satisfies AuthTokenResponse,
      },
    },
    default: {
      body: {
        error_code: "EGW00001",
        error_description: "OAuth 요청을 처리할 수 없습니다.",
      } satisfies KisOAuthErrorResponse,
    },
  },
  authWsToken: {
    method: "post",
    path: "/oauth2/Approval",
    scenarios: {
      success: {
        status: 200,
        body: {
          approval_key: "testApprovalKey",
        } satisfies AuthWsTokenResponse,
      },
    },
    default: {
      body: {
        rt_cd: "1",
        msg_cd: "KIS999",
        msg1: "KIS REST 오류 응답",
      } satisfies KisRestErrorResponse,
    },
  },
  domesticStockInquirePrice: {
    method: "get",
    path: "/uapi/domestic-stock/v1/quotations/inquire-price",
    scenarios: {
      success: {
        status: 200,
        body: {
          rt_cd: "0",
          msg_cd: "MCA00000",
          msg1: "정상처리 되었습니다.",
          output: {
            iscd_stat_cls_code: "55",
            marg_rate: "20.00",
            rprs_mrkt_kor_name: "KOSPI",
            new_hgpr_lwpr_cls_code: "",
            bstp_kor_isnm: "전기전자",
            temp_stop_yn: "N",
            oprc_rang_cont_yn: "N",
            clpr_rang_cont_yn: "N",
            crdt_able_yn: "Y",
            grmn_rate_cls_code: "40",
            elw_pblc_yn: "N",
            stck_prpr: "80000",
            prdy_vrss: "1000",
            prdy_vrss_sign: "2",
            prdy_ctrt: "1.27",
            acml_tr_pbmn: "987654321000",
            acml_vol: "12345678",
            prdy_vrss_vol_rate: "105.24",
            stck_oprc: "79000",
            stck_hgpr: "81000",
            stck_lwpr: "78000",
            stck_mxpr: "102000",
            stck_llam: "55000",
            stck_sdpr: "79000",
            wghn_avrg_stck_prc: "79850.25",
            hts_frgn_ehrt: "52.31",
            frgn_ntby_qty: "123456",
            pgtr_ntby_qty: "54321",
            pvt_scnd_dmrs_prc: "76000",
            pvt_frst_dmrs_prc: "77000",
            pvt_pont_val: "79000",
            pvt_frst_dmsp_prc: "81000",
            pvt_scnd_dmsp_prc: "82000",
            dmrs_val: "77000",
            dmsp_val: "81000",
            cpfn: "7780",
            rstc_wdth_prc: "23400",
            stck_fcam: "100",
            stck_sspr: "50000",
            aspr_unit: "100",
            hts_deal_qty_unit_val: "1",
            lstn_stcn: "5969782550",
            hts_avls: "477582",
            per: "15.23",
            pbr: "1.42",
            stac_month: "12",
            vol_tnrt: "0.21",
            eps: "5252",
            bps: "56338",
            d250_hgpr: "88800",
            d250_hgpr_date: "20260701",
            d250_hgpr_vrss_prpr_rate: "-9.91",
            d250_lwpr: "65000",
            d250_lwpr_date: "20260115",
            d250_lwpr_vrss_prpr_rate: "23.08",
            stck_dryy_hgpr: "88800",
            dryy_hgpr_vrss_prpr_rate: "-9.91",
            dryy_hgpr_date: "20260701",
            stck_dryy_lwpr: "65000",
            dryy_lwpr_vrss_prpr_rate: "23.08",
            dryy_lwpr_date: "20260115",
            w52_hgpr: "88800",
            w52_hgpr_vrss_prpr_ctrt: "-9.91",
            w52_hgpr_date: "20260701",
            w52_lwpr: "65000",
            w52_lwpr_vrss_prpr_ctrt: "23.08",
            w52_lwpr_date: "20260115",
            whol_loan_rmnd_rate: "0.12",
            ssts_yn: "Y",
            stck_shrn_iscd: "005930",
            fcam_cnnm: "100",
            cpfn_cnnm: "7780",
            apprch_rate: "90.09",
            frgn_hldn_qty: "3123456789",
            vi_cls_code: "N",
            ovtm_vi_cls_code: "N",
            last_ssts_cntg_qty: "0",
            invt_caful_yn: "N",
            mrkt_warn_cls_code: "00",
            short_over_yn: "N",
            sltr_yn: "N",
            mang_issu_cls_code: "00",
          },
        } satisfies DomesticStockInquirePriceResponse,
      },
      "error/not-found": {
        status: 200,
        body: {
          rt_cd: "1",
          msg_cd: "MCA00001",
          msg1: "조회할 수 없는 종목입니다.",
        } satisfies KisRestErrorResponse,
      },
    },
    default: {
      body: {
        rt_cd: "1",
        msg_cd: "KIS999",
        msg1: "KIS REST 오류 응답",
      } satisfies KisRestErrorResponse,
    },
  },
  domesticStockInquireDailyItemChartPrice: {
    method: "get",
    path: "/uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice",
    scenarios: {
      success: {
        status: 200,
        body: {
          rt_cd: "0",
          msg_cd: "MCA00000",
          msg1: "정상처리 되었습니다.",
          output1: {
            prdy_vrss: "1000",
            prdy_vrss_sign: "2",
            prdy_ctrt: "1.27",
            stck_prdy_clpr: "79000",
            acml_vol: "12345678",
            acml_tr_pbmn: "987654321000",
            hts_kor_isnm: "삼성전자",
            stck_prpr: "80000",
            stck_shrn_iscd: "005930",
            prdy_vol: "10000000",
            stck_mxpr: "102000",
            stck_llam: "55000",
            stck_oprc: "79000",
            stck_hgpr: "81000",
            stck_lwpr: "78000",
            stck_prdy_oprc: "78000",
            stck_prdy_hgpr: "80000",
            stck_prdy_lwpr: "77000",
            askp: "80100",
            bidp: "80000",
            prdy_vrss_vol: "2345678",
            vol_tnrt: "0.21",
            stck_fcam: "100",
            lstn_stcn: "5969782550",
            cpfn: "7780",
            hts_avls: "477582",
            per: "15.23",
            eps: "5252",
            pbr: "1.42",
            itewhol_loan_rmnd_ratem: "0.12",
          },
          output2: [
            {
              stck_bsop_date: "20260517",
              stck_clpr: "70000",
              stck_oprc: "69000",
              stck_hgpr: "71000",
              stck_lwpr: "68000",
              acml_vol: "12345678",
              acml_tr_pbmn: "864197460000",
              flng_cls_code: "00",
              prtt_rate: "0.00",
              mod_yn: "N",
              prdy_vrss_sign: "2",
              prdy_vrss: "1000",
              revl_issu_reas: "",
            },
            {
              stck_bsop_date: "20260608",
              stck_clpr: "80000",
              stck_oprc: "79000",
              stck_hgpr: "81000",
              stck_lwpr: "78000",
              acml_vol: "22345678",
              acml_tr_pbmn: "1787654240000",
              flng_cls_code: "00",
              prtt_rate: "0.00",
              mod_yn: "N",
              prdy_vrss_sign: "2",
              prdy_vrss: "1000",
              revl_issu_reas: "",
            },
          ],
        } satisfies DomesticStockInquireDailyItemChartPriceResponse,
      },
    },
    default: {
      body: {
        rt_cd: "1",
        msg_cd: "KIS999",
        msg1: "KIS REST 오류 응답",
      } satisfies KisRestErrorResponse,
    },
  },
  domesticStockChkHoliday: {
    method: "get",
    path: "/uapi/domestic-stock/v1/quotations/chk-holiday",
    scenarios: {
      success: {
        status: 200,
        body: {
          rt_cd: "0",
          msg_cd: "MCA00000",
          msg1: "정상처리 되었습니다.",
          ctx_area_fk: "",
          ctx_area_nk: "",
          output: [
            {
              bass_dt: "20260604",
              wday_dvsn_cd: "4",
              bzdy_yn: "Y",
              tr_day_yn: "Y",
              opnd_yn: "Y",
              sttl_day_yn: "Y",
            },
          ],
        } satisfies DomesticStockChkHolidayResponse,
      },
    },
    default: {
      body: {
        rt_cd: "1",
        msg_cd: "KIS999",
        msg1: "KIS REST 오류 응답",
      } satisfies KisRestErrorResponse,
    },
  },
} as const
