/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenDART
 * OpenAPI spec version: 1.0.0
 */
import * as zod from "zod/mini"

export const OpendartCorpCodeRegExp = new RegExp("^[0-9]{8}$")

export const OpendartCorpCode = /*#__PURE__*/ zod
  .string()
  .check(/*#__PURE__*/ zod.regex(OpendartCorpCodeRegExp))

export type OpendartCorpCode = zod.input<typeof OpendartCorpCode>
export type OpendartCorpCodeOutput = zod.output<typeof OpendartCorpCode>

export const OpendartErrorResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  message: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
})

export type OpendartErrorResponse = zod.input<typeof OpendartErrorResponse>
export type OpendartErrorResponseOutput = zod.output<
  typeof OpendartErrorResponse
>

export const opendartNullableStockCodeOneRegExp = new RegExp(
  "^\\s*(?:[A-Z0-9]{1,9})?\\s*$"
)

export const OpendartNullableStockCode = /*#__PURE__*/ zod.union([
  /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartNullableStockCodeOneRegExp)),
  /*#__PURE__*/ zod.null(),
])

export type OpendartNullableStockCode = zod.input<
  typeof OpendartNullableStockCode
>
export type OpendartNullableStockCodeOutput = zod.output<
  typeof OpendartNullableStockCode
>

export const OpendartCompanyResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.literal("000"),
  message: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  corp_code: OpendartCorpCode,
  corp_name: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  stock_code: /*#__PURE__*/ zod.optional(OpendartNullableStockCode),
  stock_name: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  corp_cls: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  induty_code: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  est_dt: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  acc_mt: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
})

export type OpendartCompanyResponse = zod.input<typeof OpendartCompanyResponse>
export type OpendartCompanyResponseOutput = zod.output<
  typeof OpendartCompanyResponse
>

export const opendartDisclosureRceptDtRegExp = new RegExp("^[0-9]{8}$")
export const opendartDisclosureRmDefault = ``

export const OpendartDisclosure = /*#__PURE__*/ zod.object({
  rcept_no: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  corp_code: OpendartCorpCode,
  stock_code: /*#__PURE__*/ zod.optional(OpendartNullableStockCode),
  corp_name: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  report_nm: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  flr_nm: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  rcept_dt: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartDisclosureRceptDtRegExp)),
  rm: /*#__PURE__*/ zod._default(
    /*#__PURE__*/ zod.string(),
    opendartDisclosureRmDefault
  ),
})

export type OpendartDisclosure = zod.input<typeof OpendartDisclosure>
export type OpendartDisclosureOutput = zod.output<typeof OpendartDisclosure>

export const OpendartDisclosuresResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.literal("000"),
  message: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  list: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.array(OpendartDisclosure),
      OpendartDisclosure,
    ])
  ),
})

export type OpendartDisclosuresResponse = zod.input<
  typeof OpendartDisclosuresResponse
>
export type OpendartDisclosuresResponseOutput = zod.output<
  typeof OpendartDisclosuresResponse
>

export const opendartFinancialAccountBsnsYearRegExp = new RegExp("^[0-9]{4}$")

export const OpendartFinancialAccount = /*#__PURE__*/ zod.object({
  bsns_year: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartFinancialAccountBsnsYearRegExp)),
  reprt_code: /*#__PURE__*/ zod.enum(["11013", "11012", "11014", "11011"]),
  corp_code: OpendartCorpCode,
  sj_div: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  account_id: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  account_nm: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  thstrm_amount: /*#__PURE__*/ zod.nullish(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.number(),
    ])
  ),
  frmtrm_amount: /*#__PURE__*/ zod.nullish(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.number(),
    ])
  ),
  bfefrmtrm_amount: /*#__PURE__*/ zod.nullish(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.string(),
      /*#__PURE__*/ zod.number(),
    ])
  ),
  currency: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
})

export type OpendartFinancialAccount = zod.input<
  typeof OpendartFinancialAccount
>
export type OpendartFinancialAccountOutput = zod.output<
  typeof OpendartFinancialAccount
>

export const OpendartFinancialAccountsResponse = /*#__PURE__*/ zod.object({
  status: /*#__PURE__*/ zod.literal("000"),
  message: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  list: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.array(OpendartFinancialAccount),
      OpendartFinancialAccount,
    ])
  ),
})

export type OpendartFinancialAccountsResponse = zod.input<
  typeof OpendartFinancialAccountsResponse
>
export type OpendartFinancialAccountsResponseOutput = zod.output<
  typeof OpendartFinancialAccountsResponse
>
export const opendartCompanyQueryCorpCodeRegExp = new RegExp("^[0-9]{8}$")

export const OpendartCompanyQueryParams = /*#__PURE__*/ zod.object({
  crtfc_key: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  corp_code: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartCompanyQueryCorpCodeRegExp)),
})

export const OpendartCompany200Response = /*#__PURE__*/ zod.union([
  OpendartCompanyResponse,
  OpendartErrorResponse,
])

export const OpendartCompanyDefaultResponse = OpendartErrorResponse

export const opendartDisclosuresQueryCorpCodeRegExp = new RegExp("^[0-9]{8}$")
export const opendartDisclosuresQueryBgnDeRegExp = new RegExp("^[0-9]{8}$")
export const opendartDisclosuresQueryEndDeRegExp = new RegExp("^[0-9]{8}$")

export const OpendartDisclosuresQueryParams = /*#__PURE__*/ zod.object({
  crtfc_key: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  corp_code: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartDisclosuresQueryCorpCodeRegExp)),
  bgn_de: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartDisclosuresQueryBgnDeRegExp)),
  end_de: /*#__PURE__*/ zod
    .string()
    .check(/*#__PURE__*/ zod.regex(opendartDisclosuresQueryEndDeRegExp)),
  last_reprt_at: /*#__PURE__*/ zod.literal("Y"),
  page_no: /*#__PURE__*/ zod.literal("1"),
  page_count: /*#__PURE__*/ zod.literal("100"),
})

export const OpendartDisclosures200Response = /*#__PURE__*/ zod.union([
  OpendartDisclosuresResponse,
  OpendartErrorResponse,
])

export const OpendartDisclosuresDefaultResponse = OpendartErrorResponse

export const opendartFinancialAccountsQueryCorpCodeRegExp = new RegExp(
  "^[0-9]{8}$"
)
export const opendartFinancialAccountsQueryBsnsYearRegExp = new RegExp(
  "^[0-9]{4}$"
)

export const OpendartFinancialAccountsQueryParams = /*#__PURE__*/ zod.object({
  crtfc_key: /*#__PURE__*/ zod.string().check(/*#__PURE__*/ zod.minLength(1)),
  corp_code: /*#__PURE__*/ zod
    .string()
    .check(
      /*#__PURE__*/ zod.regex(opendartFinancialAccountsQueryCorpCodeRegExp)
    ),
  bsns_year: /*#__PURE__*/ zod
    .string()
    .check(
      /*#__PURE__*/ zod.regex(opendartFinancialAccountsQueryBsnsYearRegExp)
    ),
  reprt_code: /*#__PURE__*/ zod.enum(["11013", "11012", "11014", "11011"]),
})

export const OpendartFinancialAccounts200Response = /*#__PURE__*/ zod.union([
  OpendartFinancialAccountsResponse,
  OpendartErrorResponse,
])

export const OpendartFinancialAccountsDefaultResponse = OpendartErrorResponse

const opendartCompanyContract = {
  method: "get",
  path: "/api/company.json",
  request: {
    query: OpendartCompanyQueryParams,
  },
  responses: {
    "200": {
      schema: OpendartCompany200Response,
      success: OpendartCompanyResponse,
      failures: [OpendartErrorResponse],
    },
    default: {
      schema: OpendartCompanyDefaultResponse,
    },
  },
} as const

const opendartDisclosuresContract = {
  method: "get",
  path: "/api/list.json",
  request: {
    query: OpendartDisclosuresQueryParams,
  },
  responses: {
    "200": {
      schema: OpendartDisclosures200Response,
      success: OpendartDisclosuresResponse,
      failures: [OpendartErrorResponse],
    },
    default: {
      schema: OpendartDisclosuresDefaultResponse,
    },
  },
} as const

const opendartFinancialAccountsContract = {
  method: "get",
  path: "/api/fnlttSinglAcnt.json",
  request: {
    query: OpendartFinancialAccountsQueryParams,
  },
  responses: {
    "200": {
      schema: OpendartFinancialAccounts200Response,
      success: OpendartFinancialAccountsResponse,
      failures: [OpendartErrorResponse],
    },
    default: {
      schema: OpendartFinancialAccountsDefaultResponse,
    },
  },
} as const

export const rest = {
  opendartCompany: opendartCompanyContract,
  opendartDisclosures: opendartDisclosuresContract,
  opendartFinancialAccounts: opendartFinancialAccountsContract,
} as const
